[project]
name = "user-service"
version = "0.1.0"
description = "User domain models, DTOs, and repositories"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "SQLAlchemy>=2.0",
    "pydantic>=2.4",
    "alembic>=1.12",
    "aiosqlite>=0.19",
    "pytest>=7.4",
    "pytest-asyncio>=0.23",
]

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
pythonpath = ["src"]

[tool.mypy]
python_version = "3.11"
packages = ["user_service"]
warn_unused_configs = true
warn_unused_ignores = true
strict_optional = true
no_implicit_optional = true
warn_return_any = true
disallow_untyped_defs = true
check_untyped_defs = true
mypy_path = "src"

[tool.pydantic-mypy]
init_typed = true
warn_untyped_fields = true
