global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "backend"
    metrics_path: /metrics
    static_configs:
      - targets:
          - backend:8000
  - job_name: "rabbitmq"
    metrics_path: /metrics
    basic_auth:
      username: devstack
      password: devstack
    static_configs:
      - targets:
          - rabbitmq:15692
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: ".*"
        action: keep
  - job_name: "prometheus"
    static_configs:
      - targets:
          - localhost:9090
